# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: rp2040_zero
    shield: apiaster_wired
    artifact-name: apiaster-rp2040-zero
  - board: rp2040_zero
    shield: apiaster_wired
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: apiaster-rp2040-zero-studio
  - board: rp2040_zero
    shield: apiaster_wired
    snippet: zmk-usb-logging
    artifact-name: apiaster-rp2040-logging
  - board: seeeduino_xiao_ble
    shield: apiaster_wired rgbled_adapter
    artifact-name: apiaster-xiao-ble
  - board: seeeduino_xiao_ble
    shield: apiaster_wired rgbled_adapter
    artifact-name: apiaster-xiao-ble-studio
  - board: seeeduino_xiao_ble
    shield: apiaster_left rgbled_adapter
    artifact-name: apiaster-left-xiao-ble
  - board: seeeduino_xiao_ble
    shield: apiaster_left rgbled_adapter
    snippet: studio-rpc-usb-uart 
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: apiaster-left-xiao-ble-studio
  - board: seeeduino_xiao_ble
    shield: apiaster_right rgbled_adapter
    artifact-name: apiaster-right-xiao-ble
  - board: seeeduino_xiao_ble
    shield: apiaster_left rgbled_adapter
    snippet: zmk-usb-logging
    artifact-name: apiaster-left-xiao-ble-logging
  - board: seeeduino_xiao_ble
    shield: apiaster_right rgbled_adapter
    snippet: zmk-usb-logging
    artifact-name: apiaster-right-xiao-ble-logging
  - board: seeeduino_xiao_ble
    shield: apiaster_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: apiaster-left-xiao-ble-with-dongle
  - board: seeeduino_xiao_ble
    shield: apiaster_dongle rgbled_adapter
    artifact-name: apiaster-dongle-xiao-ble
  - board: seeeduino_xiao_ble
    shield: apiaster_dongle rgbled_adapter
    snippet: studio-rpc-usb-uart 
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: apiaster-dongle-xiao-ble-studio
  - board: seeeduino_xiao_ble
    shield: apiaster_dongle rgbled_adapter
    snippet: zmk-usb-logging
    artifact-name: apiaster-dongle-xiao-ble-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao-ble-reset
  - board: rp2040_zero
    shield: settings_reset
    artifact-name: rp2040-zero-reset